### ISSUE TITLE
6.9.1. マクロ平均とマイクロ平均: 適合率と再現率が正解率と等しくなる場合

### ISSUE THREAD

**Issue by icoxfog417** [chokkan/mlnote#10]
記載は「マクロ平均」となっていますが、「マイクロ平均」が正だと思います。

https://chokkan.github.io/mlnote/classification/02multi.html#id14

![image](https://user-images.githubusercontent.com/544269/168463329-cc2ebd5c-7c8a-4190-8a80-54981118ea72.png)

**Comment by chokkan** [comment]
ありがとうございます．
